input_dir: "src"
output_dir: "Output/Build"

conversions:
  - input: Airplane.svg
    output: airplane-white-38x38.png
    background: none
    level_colors: "white,"
    resize: 38x38

  - input: Apokee.svg
    output: apokee-gray-460x460.png
    background: none
    level_colors: "#4d4d4d,"
    resize: 460x460

  - input: Apokee.svg
    output: apokee-gray-32x32.png
    background: none
    level_colors: "#4d4d4d,"
    resize: 32x32

  - input: Connection.svg
    output: connection-white-38x38.png
    background: none
    level_colors: "white,"
    resize: 38x38

  - input: HotSpot.svg
    output: hotspot-white-24x24.png
    background: none
    level_colors: "white,"
    resize: 24x24

  - input: HotSpot.svg
    output: hotspot-white-38x38.png
    background: none
    level_colors: "white,"
    resize: 38x38

  - input: Ketchup.svg
    output: ketchup-white-38x38.png
    background: none
    level_colors: "white,"
    resize: 38x38

  - input: PlaneMode.svg
    output: planemode-white-black-1978x1024.png
    background: white
    level_colors: "white,black"
    resize: 1978x1024

  - input: Rocket.svg
    output: rocket-white-38x38.png
    background: none
    level_colors: "white,"
    resize: 38x38
